{% include 'inc/header.php' %}
<div class="row contact layout">
<section>
  <div class="col-sm-5 col-md-5">
  <h1>Contact Armani Casa</h1>
  <article>
    Please write to us at: 
    <script type="text/javascript">
    part='armanicasa.com'
    part=('info' + '@' + part)
    document.write('<a href="mailto:' + part + '">' + part + '</a>')
    </script>
    <noscript>
        <em>Email address protected by JavaScript.<BR>
        Please enable JavaScript to contact me.</em>
    </noscript>
  </article>
 </div>
</section>
</div>
{% include 'inc/footer.php' %}